version: '3.7'
# 网络配置
networks:
  backend: 

# 服务容器配置
services:
  hyperf:
    image: hyperf/hyperf:8.1-alpine-v3.16-swoole
    container_name: "hyperf"
    volumes:
      - ./:/app                          # 把容器内/app目錄挂載在當前文件夾
    working_dir: /app                    # 設置容器工作目錄 即docker exec 進去默認的目錄
    ports:                               # 设置端口映射 暂时支持最多3个服务运行 不够自己再加
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
    networks:                            # 
      - backend
    privileged: true
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    restart: always

  dbcenter:
    image: mysql/mysql-server:5.7
    container_name: "dbcenter"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "hyperf"
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ./devenv/data/mysql:/var/lib/mysql        # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Mysql 数据的目录挂载到容器中 /var/lib/mysql 目录
      - ./devenv/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis
    container_name: "redis"
    environment:
      TZ: "Asia/Shanghai"
    privileged: true
    volumes:
      - ./devenv/data/redis:/data                 # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Redis 数据的目录挂载到容器中 /data 目录
    networks:
      - backend
    restart: always
